// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imyzcwgskjngwvcadrjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlteXpjd2dza2puZ3d2Y2FkcmpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODk2ODQsImV4cCI6MjA3MjU2NTY4NH0.eVrnAk_Izo9hYdAFvuXxBH28OrT23cM26eoJfGVqPS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});